### PR TITLE
Hotfix nodemon file

### PR DESCRIPTION
**Pull request by leodonny**

### CODE REVIEW

**Review by hussein-aitlahcen — DISMISSED** [review]

**Comment by hussein-aitlahcen** [comment]
@leodonny can you rebase the branch please, github cannot rebase/merge it as it is :).

**Comment by leodonny** [comment]
@hussein-aitlahcen  And what about now ? It should be ok

**Comment by hussein-aitlahcen** [comment]
@leodonny [here is the documentation](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) explaining how to rebase (and what's the difference with merge commit).
Please look at it and tell me if this seems ok to you !

**Comment by leodonny** [comment]
@hussein-aitlahcen you should fill CONTRIBUTING.md with this doc and explain the process succinctly

**Review by mister-good-deal — APPROVED** [review]

**Pull request merged**
